name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Log in to Docker Hub
      run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      env:
        DOCKER_USERNAME: rithwwik
        DOCKER_PASSWORD: docker123
    - name: Build the Docker image
      run: docker build -t login-app . -f Dockerfile
    - name: Tag the Docker image
      run: docker tag login-app rithwwik/login-app:latest
    - name: Push the Docker image to Docker Hub
      run: docker push rithwwik/login-app:latest
