name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      env:
        DOCKER_USERNAME: rithwwik
        DOCKER_PASSWORD: docker123

    - name: Set Semantic Version Tag
      id: semantic_tag
      run: |
        # Fetch the latest semantic version tag from Docker Hub
        latest_tag=$(curl -s https://registry.hub.docker.com/v2/repositories/rithwwik/login-app/tags \
          | jq -r '.results[].name' \
          | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+$' \
          | sort -rV \
          | head -n 1)

        # If no tags exist, start from v0.0.0
        if [ -z "$latest_tag" ]; then
          latest_tag="v0.0.0"
        fi

        # Parse the latest tag and increment the patch version
        major=$(echo $latest_tag | cut -d. -f1 | sed 's/v//')
        minor=$(echo $latest_tag | cut -d. -f2)
        patch=$(echo $latest_tag | cut -d. -f3)
        new_patch=$((patch + 1))

        # Define the new semantic version tag
        new_tag="v${major}.${minor}.${new_patch}"
        echo "new_tag=$new_tag" >> $GITHUB_ENV
        echo "New semantic tag: $new_tag"

    - name: Build the Docker image
      run: docker build -t login-app . -f Dockerfile

    - name: Tag the Docker image
      run: |
        docker tag login-app rithwwik/login-app:latest
        docker tag login-app rithwwik/login-app:${{ env.new_tag }}

    - name: Push the Docker image to Docker Hub
      run: |
        docker push rithwwik/login-app:latest
        docker push rithwwik/login-app:${{ env.new_tag }}
